<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>ImpactJS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.variable.impact.namespace</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.impact</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(ig)\.(module)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.impact</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.(requires|defines|extend)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.variable.impact.namespace</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(ig)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.impact.entity</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Entity[a-zA-Z0-9]+)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.impact</string>
	<key>uuid</key>
	<string>fadaa18d-154c-45fb-98e3-64c3f4e4cbeb</string>
</dict>
</plist>
