<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>name</key>
	<string>ImpactJS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(ig)\.(module)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.variable.impact.namespace</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.impact</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\b</string>
			<key>name</key>
			<string>meta.module.impact</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>['"]\b(.+)\b['"]</string>
					<key>name</key>
					<string>entity.name.impact.module</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\.\s*(requires)\s*\((?=\s*['"a-zA-Z0-9\.\,\s]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.impact</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)(?=(\.\s*defines)?)</string>
					<key>name</key>
					<string>meta.module.impact.requirements</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>['"][\w\.]+['"]</string>
							<key>name</key>
							<string>entity.name.requirement</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(defines)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.impact</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\);</string>
					<key>name</key>
					<string>meta.module.impact.definition</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ImpactEntity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ImpactExtend</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ImpactEntity</key>
		<dict>
			<key>match</key>
			<string>\big.Entity\b</string>
			<key>name</key>
			<string>support.class.impact.entity</string>
		</dict>
		<key>ImpactExtend</key>
		<dict>
			<key>match</key>
			<string>\bextend\b</string>
			<key>name</key>
			<string>support.function.impact</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.js.impact</string>
	<key>uuid</key>
	<string>fadaa18d-154c-45fb-98e3-64c3f4e4cbeb</string>
</dict>
</plist>
