<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>name</key>
	<string>ImpactJS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(ig)\.(module)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.variable.impact.namespace</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.impact</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b\)\b</string>
			<key>name</key>
			<string>meta.module.impact</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>['"]\b(.+)\b['"]</string>
					<key>name</key>
					<string>entity.name.impact.module</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(requires)\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.impact</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b\)\.\b</string>
					<key>name</key>
					<string>meta.module.impact.requirements</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>['"]\b(.+)\b['"]</string>
							<key>name</key>
							<string>entity.name.impact.module.requirement</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\bdefine\b</string>
					<key>name</key>
					<string>support.function.impact</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.impact</string>
	<key>uuid</key>
	<string>fadaa18d-154c-45fb-98e3-64c3f4e4cbeb</string>
</dict>
</plist>
